Functions for data visualizations
catalystneuro/distributed-coding-matnwb pull request #10
Opened 2021-08-16 14:41 UTC by Vigneswaran-Chandrasekaran

Function for plotting PSTH

**Sample usecase:**
```matlab
nwb_file = nwbRead('nicklab~Subjects~Hench~2017-06-16~001~alf.nwb');
unit_id = 7;
before_time = -10
after_time = 5
group_by = 'response_choice';
num_bins = 50;
psth(nwb_file, unit_id, before_time, after_time, group_by, num_bins);
```
will give an output plot,
![psth](https://user-images.githubusercontent.com/33456057/129581553-b24f5bf0-fc1c-4f67-935b-6c1a3aaf8ff7.png)

2021-08-16 15:18 UTC, bendichter commented on psth.m
> +                this_bin_counter = histcounts([before_time, row_data, ...
try using the edge parameter

2021-08-16 15:18 UTC, bendichter commented on psth.m
> +                this_bin_counter = histcounts([before_time, row_data, ...
something like edges = linespace(before_time, after_time, nbins + 1);

2021-08-16 15:19 UTC, bendichter commented
only have xlabel on last tile

2021-08-16 15:20 UTC, bendichter commented
please add a docstring to the function

2021-08-18 17:21 UTC, Vigneswaran-Chandrasekaran commented
Added some stylistic changes and used bin edges for histogram plotting to improve readability

The current version will give an output plot similar to,

![psth](https://user-images.githubusercontent.com/33456057/129942999-d0492495-bb63-4c20-9c47-c21ba55094d7.png)

2021-08-18 22:28 UTC, bendichter commented
@Vigneswaran-Chandrasekaran awesome! Is it ready for me to take a look?

2021-08-19 09:28 UTC, Vigneswaran-Chandrasekaran commented
I've added Normal distribution plot but I am not sure that is the right way to do it! Other than the distribution part, I think now the PR is ready for your review :)

Now the plot along with the distribution subplot looks like,
![sample_plot](https://user-images.githubusercontent.com/33456057/130044182-a1c4cb40-1c06-411b-b7c2-fa78adc130f6.png)

As the data points are close to uniform across, the bell curve is not very good looking

2021-08-19 12:58 UTC, bendichter commented
@Vigneswaran-Chandrasekaran getting the smoothed curve is pretty tricky. You actually want to convolve a a gaussian over the average spike train for the trial group. If that's too tricky, I think a PSTH is fine, but this graph isn't really right.

2021-08-19 13:00 UTC, bendichter commented
Could you set the default number of bins to 30, and the default start and stop times to -0.5 and 1.0 seconds?

2021-08-23 14:55 UTC, Vigneswaran-Chandrasekaran commented
Added a simple GUI interface to plot. The interface looks something to,

<img width="242" alt="gui" src="https://user-images.githubusercontent.com/33456057/130469267-94096153-dde3-4a6e-a6c6-672ed9c62159.png">

2021-08-23 15:29 UTC, bendichter commented
@Vigneswaran-Chandrasekaran this looks great! Would you be able to allow group_by to be optional, and if it is missing do not group the trials at all and have them all be black?

2021-08-23 16:58 UTC, Vigneswaran-Chandrasekaran commented
> @Vigneswaran-Chandrasekaran this looks great! Would you be able to allow group_by to be optional, and if it is missing do not group the trials at all and have them all be black?

Sure, currently the y axis is trials, in no `group_by` will the y axis be simply stacking of all `group_by` variables in all trials?

2021-08-23 17:00 UTC, bendichter commented
@Vigneswaran-Chandrasekaran yes, that's right

2021-08-24 14:29 UTC, Vigneswaran-Chandrasekaran commented
I applied Gaussian filter with `sigma = 0.05` and got some satisfactory curves 😃  but I am not sure whether it is correct?

The main doubt, I have is should the time axis be, 
```linspace(start_time, stop_time, num_bins)```  or ```linspace(start_time, stop_time, sampling_rate)```, currently I used mid-points of bin edges

![untitled](https://user-images.githubusercontent.com/33456057/130634268-928300ce-7dc7-4fa9-baeb-97d5e5ac7a7a.png)
![snap](https://user-images.githubusercontent.com/33456057/130634814-8f721337-22c6-4ba7-ac19-0c4e95020686.png)

2021-08-24 14:47 UTC, bendichter commented
@Vigneswaran-Chandrasekaran this looks great!

* For timepoints, it doesn't really matter how many you use as long as you use enough that the curve appears to be smooth. I usually use 1000 points. Make sure that the gaussian kernel is a parameter that you can set.

2021-08-30 18:48 UTC, bendichter commented
Can you make it so the standard deviation is expressed in seconds, not samples?

2021-08-31 01:43 UTC, bendichter commented
Are you getting roughly the same values for the convolution compared to the histogram approach?

2021-09-21 14:29 UTC, bendichter commented
If you are getting very different values then you are probably doing the gaussian blur incorrectly

2021-09-21 14:46 UTC, Vigneswaran-Chandrasekaran commented
Thanks for your reply

The gaussian blur curve and histograms come closer as number of bins is closer to 1000 (gaussian blur's default time points)

![bins_30](https://user-images.githubusercontent.com/33456057/134192089-ad523654-8879-4e07-9458-90fad37d0606.png)

histogram with 30 bins
![30_bins_hist](https://user-images.githubusercontent.com/33456057/134192539-720eff32-7401-4546-881b-98b218abf9f4.png)

histogram with 500 bins
![500_bins](https://user-images.githubusercontent.com/33456057/134192598-a3d54bcc-19a7-40c9-9a0c-abee9ebc3f8c.png)

histogram with 1000 bins
![1k](https://user-images.githubusercontent.com/33456057/134192665-52ff32b8-431c-46ed-92a3-f673c62a4f32.png)

Am I making any sense? If not kindly mention, I will try to check the gaussian smoothing function

2021-09-21 15:09 UTC, bendichter commented
What about if there are not many bins? Like what if there are 30 bins?

2021-09-21 15:10 UTC, bendichter commented
The average rate should not change when you change the bin width of our histogram. I think you are calculating firing rate incorrectly. Are you properly dividing by the bin width in seconds?

2021-09-21 15:41 UTC, Vigneswaran-Chandrasekaran commented
>What about if there are not many bins? Like what if there are 30 bins?

 The firing rate is larger compared to the gaussian (the first figure in previous comment)

>The average rate should not change when you change the bin width of our histogram. I think you are calculating firing rate incorrectly. Are you properly dividing by the bin width in seconds?

Yes, I divide the bin widths properly (```linspace(before_time, after_time, 1000)``` for gaussian blur), I will check once where I am going wrong

2021-11-01 15:22 UTC, Vigneswaran-Chandrasekaran commented
I modified the layout of the subplots and now the plots look something similar to,

![sample1](https://user-images.githubusercontent.com/33456057/139695935-5d8e2e17-fcc9-4a27-a9d9-6731b13d7ffd.png)

![sample2](https://user-images.githubusercontent.com/33456057/139695902-3e701052-4086-4f4f-904e-01478fa53fb1.png)


Please let me know if any changes need to be done

2021-11-03 16:42 UTC, bendichter commented
@Vigneswaran-Chandrasekaran can you please resolve the merge conflicts?

2021-11-06 07:47 UTC, Vigneswaran-Chandrasekaran commented
I've resolved all the merge conflicts and it is ready for review

2021-11-06 15:30 UTC, bendichter commented on psth.m
> +%    trial start times
What do you mean by this? Do you mean that before_time and after_time should be in seconds? Because the trail start times are always in seconds.

2021-11-06 15:31 UTC, bendichter commented on psth.m
> +              psth_plot_option, std)
Usually, the comments describing the function go below the function definition line. See [documentation here](https://www.mathworks.com/help/matlab/matlab_prog/add-help-for-your-program.html)

2021-11-06 15:33 UTC, bendichter commented on psth.m
> +              psth_plot_option, std)
Could you use the [inputParser](https://www.mathworks.com/help/matlab/ref/inputparser.html)?

2021-11-08 14:15 UTC, Vigneswaran-Chandrasekaran commented on psth.m
> +%    trial start times
Yes, I meant they both should be of the same unit. I will remove it

2021-11-08 14:17 UTC, Vigneswaran-Chandrasekaran commented on psth.m
> +              psth_plot_option, std)
I use [argument block](https://in.mathworks.com/help/matlab/ref/arguments.html) similar to inputParser, should I change to inputParser?

2021-11-08 14:28 UTC, bendichter requested changes

2021-11-08 14:28 UTC, bendichter commented on psth.m
> +%    trial start times
yes, but start_times is _always_ in seconds, so you might as well just say they must be in seconds.

2021-11-08 14:57 UTC, Vigneswaran-Chandrasekaran commented on psth.m
> +              psth_plot_option, std)
I checked the documentation and it seems we can't use key-value pairs unless we pass every argument in key-value format
For example,
```functionName(arg1 = value1, arg2 = value2)``` is allowed, but
```functionName(value1, arg2=value2)``` is not allowed

2021-11-08 15:03 UTC, bendichter commented on psth.m
> +              psth_plot_option, std)
what about this?

![image](https://user-images.githubusercontent.com/844306/140765827-c046bade-abbe-4dbc-bf37-ae59575771d9.png)

2021-11-08 15:12 UTC, Vigneswaran-Chandrasekaran commented on psth.m
> +              psth_plot_option, std)
yes, but we can't do something like,
```myRectangle(4, 5, ":")```
is that fine?

2021-11-08 17:11 UTC, bendichter commented on psth.m
> +%      psth_plot_option, std);
```suggestion
% EXAMPLE
% nwb_file = nwbRead('example.nwb');
%
% PSTH( ...
%     nwb_file, ...
%     unit_id=5, ...
%     group_by='visual_stimulus_left_contrast', ...
%     before_time=-0.5, ...
%     after_time=1.0, ...
%     n_bins=50, ...
%     psth_plot_option='gaussian', ...
%     std=0.05);
```

2021-11-08 17:12 UTC, bendichter requested changes

2021-11-08 17:12 UTC, bendichter commented on psth.m
> +              psth_plot_option, std)
see the suggestion above

2021-11-10 16:28 UTC, bendichter commented on psth.m
> +function psth(nwb, options)
why did you change this to a structure?

2021-11-10 16:38 UTC, Vigneswaran-Chandrasekaran commented on psth.m
> +function psth(nwb, options)
I changed it to allow `key-value pairs` arguments [like you suggested](https://github.com/catalystneuro/distributed-coding-matnwb/pull/10#discussion_r744929857)

2021-11-10 16:52 UTC, bendichter commented on psth.m
> +%    std = 0.03);
this is what I meant by key-value pairs

2021-11-10 17:35 UTC, merged